  <table class="navi3">
    <tr>
      <td class="navi3_2">Fairway to Mallorca
      </td>
    </tr>
    <tr>
      <td class="navi3_3">&nbsp;&nbsp; <a href="http://www.mallorca-finca-reisen.de/index.htm">Home</a>
      </td>
    </tr>
    <tr>
      <td class="navi3_3">&nbsp;&nbsp; <a href="http://www.mallorca-finca-reisen.de/service/service.htm">Service</a>
      </td>
    </tr>
    <tr>
      <td class="navi3_4">&nbsp;&nbsp; &nbsp;&nbsp; <a href="http://www.mallorca-finca-reisen.de/service/wellness.htm">Wellness</a>
      </td>
    </tr>
    <tr>
      <td class="navi3_4">&nbsp;&nbsp; &nbsp;&nbsp; <a href="http://www.mallorca-finca-reisen.de/service/bonus.htm">Bonus</a>
      </td>
    </tr>
    <tr>
      <td class="navi3_4">&nbsp;&nbsp; &nbsp;&nbsp; <a href="http://www.mallorca-finca-reisen.de/service/bedienung.htm">Webseitenbedienung</a>
      </td>
    </tr>
    <tr>
      <td class="navi3_3">&nbsp;&nbsp; <a href="http://www.mallorca-finca-reisen.de/objekte/uebersicht.htm">Objekt&uuml;bersicht</a>
      </td>
    </tr>
    <!--<tr>
      <td class="navi3_4">Bis 4 Personen
      </td>
    </tr>
    <tr>
      <td class="navi3_4">Bis 8 Personen
      </td>
    </tr>
    <tr>
      <td class="navi3_4">Über 8 Personen
      </td>
    </tr>-->
    <tr>
      <td class="navi3_3">&nbsp;&nbsp; <a href="http://www.mallorca-finca-reisen.de/disclaimer/anfrage.htm">Anfrage</a>
      </td>
    </tr>
    <tr>
      <td class="navi3_3">&nbsp;&nbsp; <a href="http://www.mallorca-finca-reisen.de/lastminute/lastminute.htm">Lastminute & more</a>
      </td>
    </tr>
    <!--<tr>
      <td class="navi3_3">Mietfahrzeuge
      </td>
    </tr>-->
    <tr>
      <td class="navi3_3">&nbsp;&nbsp; <a href="http://www.mallorca-finca-reisen.de/disclaimer/ueber_uns.htm">&Uuml;ber uns</a>
      </td>
    </tr>
    <!--<tr>
      <td class="navi3_3">Reiseversicherung
      </td>
    </tr>
    <tr>
      <td class="navi3_3">Gästebuch
      </td>
    </tr>-->
    <tr>
      <td class="navi3_2">Kontakt
      </td>
    </tr>
    <tr>
      <td class="navi3_3">&nbsp;&nbsp; <a href="mailto:info@mallorca-finca-reisen.de">E-Mail</a>
      </td>
    </tr>
    <tr>
      <td class="navi3_3">&nbsp;&nbsp; <a href="http://www.mallorca-finca-reisen.de/kontakt/anrufen.htm">Rufen Sie uns an</a>
      </td>
    </tr>
    <!--<tr>
      <td class="navi3_3">Newsletter
      </td>
    </tr>-->
    <tr>
      <td class="navi3_3">&nbsp;&nbsp; <a href="http://www.mallorca-finca-reisen.de/disclaimer/impressum.htm">Impressum</a>
      </td>
    </tr>
    <tr>
      <td class="navi3_2">Impressionen
      </td>
    </tr>
    <tr>
      <td class="navi3_3">&nbsp;&nbsp; <a href="http://www.mallorca-finca-reisen.de/ortsinfos/ortsinfos.htm">Ortsinfos Es Trenc!</a>
      </td>
    </tr>
    <tr>
      <td class="navi3_2">Surftips
      </td>
    </tr>
    <tr>
      <td class="navi3_3">&nbsp;&nbsp; <a href="http://www.mallorca-finca-reisen.de/artikel/artikel.htm">Partnersites</a>
      </td>
    </tr>
    <tr>
      <td>
      <center>
      <SCRIPT type='text/javascript' language='JavaScript' src='http://xslt.alexa.com/site_stats/js/t/a?url=www.mallorca-finca-reisen.de'></SCRIPT>
      </center>
      </td>
    </tr>
  </table>