         <center>
         <table class="kopf" border="0">
          <tr >
           <td rowspan="2" valign="middle">
           <a href="http://www.mallorca-finca-reisen.de/index.htm">
           <img src="http://www.mallorca-finca-reisen.de/mimes/images/logo_ol.jpg" width="125" height="78" border="1" alt="Fairway to Mallorca - Home"></a>
           </td>
           <td align="left"><img src="http://www.mallorca-finca-reisen.de/mimes/images/Home_NBanner_1.gif" width="570" height="40" border="0" alt="">
           </td>
         </tr>
          <tr>
           <td>
           	<a href="http://www.mallorca-finca-reisen.de/objekte/haus/uebersicht.htm">Fincas</a> ::
                 <!--Ferienwohnungen-->
                 <a href="http://www.mallorca-finca-reisen.de/objekte/hotel/uebersicht.htm">Landhotels</a> ::
                 <a href="http://www.mallorca-finca-reisen.de/disclaimer/anfrage.htm">Anfrage</a> ::
                 <a href="http://www.mallorca-finca-reisen.de/kontakt/anrufen.htm">Kontakt</a> ::
                 <!--Newsletter-->

           </td>
         </tr>
	</table>
	</center>